# 应用名称
spring.application.name: demo

spring:
  profiles:
    #    active: @profiles.active@
    active: dev
#jwt:
#  # token过期时间
#  expiration: 30
#  # token加密密钥
#  secret: 123456
base:
  cache: memory




